stages:
  - build
  - test

build_job:
  stage: build
  script:
    - mvn package -Dmaven.test.skip=true
  artifacts:
    paths:
      - target/floodlight.jar
    expire_in: 1 day

test_job:
  stage: test
  script:
  - mvn test
